name: keyboard_shortcuts
description: A new Flutter package project.
version: 0.0.1
author: Antoine MARCEL <amarcel.pro@gmail.com>
homepage: https://github.com/AntoineMarcel/keyboard_shortcuts

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter