name: keyboard_shortcuts
description: Widget that allow you to use shortcuts for your application. Custom shortcuts that you define by yourself and global like auto scroll to bottom and top, navigation to home page and go to last page.
version: 0.1.0
author: Antoine MARCEL <amarcel.pro@gmail.com>
homepage: https://github.com/AntoineMarcel/keyboard_shortcuts

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter